@echo off
echo [BUILD] Assembling Stage 1 MBR...
nasm -f bin boot_mbr.asm -o boot_mbr.bin
echo [BUILD] Assembling Stage 2 Loader...
nasm -f bin boot_loader.asm -o boot_loader.bin
echo [BUILD] Assembling 64-bit Kernel...
nasm -f bin kernel64.asm -o kernel64.bin
echo [BUILD] Creating Bootable Image...
copy /b boot_mbr.bin + boot_loader.bin + kernel64.bin mominos.img
echo [DONE] MominOS Pro-X Image Created.
