"""Export Model Configuration as C Header — generates src/ai/model_config.h.

Produces a C header with all model architecture constants,
Q8_0 quantization parameters, and tensor name macros.

The C inference engine includes this header to know the exact
memory layout: weights, KV cache, attention masks, etc.
"""
import os
import sys
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from train_moe.config import MominoMoEConfig


MOM1_HEADER = """/**
 * MOMINOS MODEL CONFIGURATION
 * Auto-generated by training/convert/export_config.py
 * Model: MominoMoE-1.2B
 *
 * This header defines all constants needed by the C inference engine
 * to load and run the model. Must match the model architecture exactly.
 *
 * Memory layout:
 *   - Weights: loaded from .mom file (Q8_0 block format)
 *   - KV cache: allocated at runtime (fp16)
 *   - Activations: on stack / temp buffer
 *
 * Q8_0 Block Format (per block of 32 weights):
 *   int8_t  values[32];   // quantized weights
 *   float16 scale;        // = max_abs / 127.0
 *
 * Q8_0 dequant: w_f32[i] = (float)values[i] * scale
 */

#ifndef MOMINOS_MODEL_CONFIG_H
#define MOMINOS_MODEL_CONFIG_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* ─── Architecture Constants ──────────────────────────────────────────────── */
"""

MOM1_FOOTER = """
#ifdef __cplusplus
}}
#endif

#endif /* MOMINOS_MODEL_CONFIG_H */
"""


def generate_config_header(config: Optional[MominoMoEConfig] = None,
                           output_path: Optional[str] = None) -> str:
    """Generate the model_config.h C header content.

    Args:
        config: Model configuration (uses defaults if None)
        output_path: If set, write to this file
    Returns:
        The C header text
    """
    if config is None:
        config = MominoMoEConfig()

    total_params = config.total_params_estimate

    defines = [
        ("MODEL_VOCAB_SIZE", config.vocab_size),
        ("MODEL_D_MODEL", config.d_model),
        ("MODEL_N_LAYERS", config.n_layers),
        ("MODEL_N_HEADS", config.n_heads),
        ("MODEL_N_KV_HEADS", config.n_kv_heads),
        ("MODEL_HEAD_DIM", config.head_dim),
        ("MODEL_D_FF", config.d_ff),
        ("MODEL_N_EXPERTS", config.n_experts),
        ("MODEL_TOP_K", config.top_k),
        ("MODEL_N_SHARED_EXPERTS", config.n_shared_experts),
        ("MODEL_CONTEXT_LEN", config.context_len),
        ("MODEL_ROPE_BASE", config.rope_base),
        ("MODEL_RMS_EPS", config.rms_eps),
        ("MODEL_TOTAL_PARAMS_M", int(total_params['total_m'])),
        ("MODEL_ACTIVE_PARAMS_M", int(total_params['active_m'])),
    ]

    # Derived constants
    qk_dim = config.head_dim
    v_dim = config.head_dim
    kv_dim = config.n_kv_heads * config.head_dim
    kv_cache_bytes = (
        config.context_len * kv_dim * config.n_layers * 2 * 2  # K+V, fp16, 2 bytes per value
    )
    n_groups = config.n_heads // config.n_kv_heads

    derived = [
        ("MODEL_QK_DIM", qk_dim, "# Attention query/key dimension per head"),
        ("MODEL_V_DIM", v_dim, "# Attention value dimension per head"),
        ("MODEL_KV_DIM", kv_dim, "# KV projection dimension (n_kv_heads * head_dim)"),
        ("MODEL_N_GROUPS", n_groups, "# GQA groups = n_heads / n_kv_heads"),
        ("MODEL_KV_CACHE_BYTES", kv_cache_bytes, "# Total KV cache size in bytes (fp16)"),
        ("MODEL_EXPERT_PARAMS", config.d_model * config.d_ff * 3,
         "# Parameters per expert (gate+up+down)"),
    ]

    # Q8_0 constants
    q8_constants = [
        ("Q8_0_BLOCK_SIZE", 32),
        ("Q8_0_BLOCK_BYTES", 34, "# 32 int8 + 1 float16 scale"),
    ]

    lines = [MOM1_HEADER]

    # Model name
    lines.append("/* Model: MominoMoE-1.2B */\n")
    lines.append(f"#define MODEL_NAME \"MominoMoE-1.2B\"\n")

    # Integer defines
    lines.append("/* ─── Integer constants ─── */\n")
    for name, val in defines:
        if isinstance(val, float):
            continue  # float handled separately
        lines.append(f"#define {name:<35s} {val}\n")

    lines.append("\n")
    lines.append("/* ─── Float constants ─── */\n")
    for name, val in defines:
        if isinstance(val, float):
            # Format: small floats like 1e-5
            lines.append(f"#define {name:<35s} {val}F\n")

    lines.append("\n")
    lines.append("/* ─── Derived constants ─── */\n")
    for entry in derived:
        name = entry[0]
        val = entry[1]
        comment = entry[2] if len(entry) > 2 else ""
        lines.append(f"#define {name:<35s} {val}{'  ' + comment if comment else ''}\n")

    lines.append("\n")
    lines.append("/* ─── Q8_0 quantization ─── */\n")
    for entry in q8_constants:
        name = entry[0]
        val = entry[1]
        comment = entry[2] if len(entry) > 2 else ""
        lines.append(f"#define {name:<35s} {val}{'  ' + comment if comment else ''}\n")

    lines.append("\n")
    lines.append("/* ─── Parameter memory layout ─── */\n")
    lines.append("/* Total weights at Q8_0: ~{:.2f} GB */\n".format(total_params['q8_0_gb']))
    lines.append("/* Total params: ~{:.1f}M  |  Active per token: ~{:.1f}M */\n".format(
        total_params['total_m'], total_params['active_m']))
    lines.append("/* KV cache (fp16, {} ctx): ~{:.1f} MB */\n".format(
        config.context_len, total_params['kv_cache_mb']))
    lines.append("\n")

    # KV cache layout documentation
    lines.append("""/* ─── KV Cache Layout ─── */
/*
 * The KV cache is structured as:
 *   cache_k[layer][batch][head][seq][dim]  -- fp16
 *   cache_v[layer][batch][head][seq][dim]  -- fp16
 *
 * Where:
 *   layer = MODEL_N_LAYERS (20)
 *   batch = 1 (autoregressive)
 *   head  = MODEL_N_KV_HEADS (4)
 *   seq   = MODEL_CONTEXT_LEN (2048)
 *   dim   = MODEL_HEAD_DIM (64)
 *
 * Total size: {:.1f} MB per K or V cache
 */
""".format(total_params['kv_cache_mb'] / 2))

    # Tensor name macros
    lines.append("""/* ─── Tensor names (matching .mom file) ─── */
/* Embedding */
#define TENSOR_TOKEN_EMBED  "token_embed.weight"

/* Final norm */
#define TENSOR_FINAL_NORM   "model.norm.weight"

/* LM head */
#define TENSOR_LM_HEAD      "lm_head.weight"

/* Per-layer tensor name format strings (use snprintf to format) */
#define TENSOR_ATTN_WQ       "layers.%d.attn.wq.weight"
#define TENSOR_ATTN_WK       "layers.%d.attn.wk.weight"
#define TENSOR_ATTN_WV       "layers.%d.attn.wv.weight"
#define TENSOR_ATTN_WO       "layers.%d.attn.wo.weight"
#define TENSOR_ATTN_NORM     "layers.%d.attn_norm.weight"
#define TENSOR_FFN_NORM      "layers.%d.ffn_norm.weight"

#define TENSOR_MOE_ROUTER       "layers.%d.moe.router.weight"
#define TENSOR_MOE_SHARED_GATE  "layers.%d.moe.shared.gate.weight"
#define TENSOR_MOE_SHARED_UP    "layers.%d.moe.shared.up.weight"
#define TENSOR_MOE_SHARED_DOWN  "layers.%d.moe.shared.down.weight"

#define TENSOR_MOE_EXPERT_GATE  "layers.%d.moe.experts.%d.gate.weight"
#define TENSOR_MOE_EXPERT_UP    "layers.%d.moe.experts.%d.up.weight"
#define TENSOR_MOE_EXPERT_DOWN  "layers.%d.moe.experts.%d.down.weight"
""")

    lines.append(MOM1_FOOTER)

    header_text = "".join(lines)

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(header_text)
        print(f"Wrote {output_path} ({len(header_text)} bytes)")

    return header_text


def main():
    """CLI entry point."""
    config = MominoMoEConfig()

    # Default output path: src/ai/model_config.h (relative to project root)
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    output_path = os.path.join(project_root, "src", "ai", "model_config.h")

    header_text = generate_config_header(config, output_path)
    print(f"Generated {len(header_text)} bytes of C header")


if __name__ == "__main__":
    main()